# AutoOrganize 插件配置文件 - 静默模式示例
# 将不需要的消息设置为空字符串即可禁用

# 性能设置
performance:
  # 每tick扫描的方块数量
  blocks_per_tick: 500

# 视觉效果设置
visual_effects:
  # 是否启用物品飞行动画
  enabled: true
  # 飞行持续时间（tick）
  flight_duration: 30
  # 物品缩放大小
  item_scale: 0.3

messages:
  # GUI相关消息
  gui_open: "§a请将需要整理的物品放入界面中，关闭界面后将自动开始整理"
  gui_start_organizing: ""  # 禁用开始整理消息
  gui_no_items: "§c没有检测到需要整理的物品"
  
  # 整理过程消息
  search_containers: ""  # 禁用搜索容器消息
  containers_found: "§a找到 {count} 个容器，开始整理物品..."
  no_containers: "§c未找到任何容器，物品已返回背包"
  organizing_progress: ""  # 禁用进度消息
  
  # 完成消息
  organize_complete: "§a整理完成！"
  items_organized: ""  # 禁用已整理物品数量消息
  items_remaining: "§e剩余物品: {count} 种（已返回背包）"
  all_items_organized: "§a所有物品都已成功整理！"
  
  # 错误消息
  error_occurred: "§c整理过程中发生错误，请稍后重试"
  player_only: "此命令只能由玩家执行"
