name: AutoOrganize
api: "1.21"
version: "1.0"
main: org.etwxr9.autoorganize.AutoOrganize
api-version: '1.21'
softdepend: [CoreProtect, LockettePro]
commands:
  organize:
    description: Organize items with coordinates
    usage: /organize <coordinates> <range>
